apiVersion: v1
kind: Secret
metadata:
  name: cscs-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:

  # ── Shared: MySQL ───────────────────────────────────────────────────────────
  MYSQL_DB_PASSWORD:       "{{ .Values.mysql_db_password }}"

  # ── auth-server ─────────────────────────────────────────────────────────────
  GOOGLE_OAUTH_SECRET_KEY: "{{ .Values.google_oauth_secret_key }}"

  # ── notification-api ────────────────────────────────────────────────────────
  SEND_GRID_PASSWORD:      "{{ .Values.send_grid_password }}"