apiVersion: v1
kind: Secret
metadata:
  name: flat5-secret
  namespace: flat5-dev
type: Opaque
data:

 
  MYSQL_DB_PASSWORD:       ZmxhdDVkZXZwYXNz

  # ── auth-server ─────────────────────────────────────────────────────────────
  GOOGLE_OAUTH_SECRET_KEY: ZmxhdDUtZGV2LW9hdXRoLXNlY3JldA==

  # ── notification-api ────────────────────────────────────────────────────────
  SEND_GRID_PASSWORD:      ZmxhdDUtZGV2LXNlbmRncmlkLWtleQ==